// deploy code will go here
const HDWalletProvider = require('truffle-hdwallet-provider');
const Web3 = require('web3');
const { interface, bytecode } = require('./compile');

const provider = HDWalletProvider('WALLET MNEMONIC GOES HERE', 'INFURA ENDPOINT GOES HERE');

const web3 = new Web3(provider);

const deploy = async () => {

  // Get a list of all accounts (that can be generated by the mnemonic)
  const accounts = await web3.eth.getAccounts();

  console.log("Attempting to deploy from account", accounts[0]);

  // Use one of the accounts to deploy the contract
  const result = await new web3.eth.Contract(JSON.parse(interface))
    .deploy({ data: bytecode, arguments: ['Hey Anthony! :)'] })
    .send({ from: accounts[0], gas: '1000000', gasPrice: '500000000' });

  console.log('Contract deployed to', result.options.address);
};
deploy();